### ISSUE TITLE
main.c 파일 속_getch() 함수의 존재 이유가 모호합니다.

### ISSUE THREAD

**Issue by 4z7l** [myujin/OSS-Snake#13]
_getch()함수를 표준함수로 바꾸기위한 작업 진행중에 있으나,
_getch()함수를 삭제해도 게임 진행이 잘 되는것 같아 
_getch() 삭제 시 오류가 있는지 확인해보고, 없으면 이 함수를 제거하고자 합니다.

**Comment by myujin** [comment]
예전에 코드 리뷰를 해보았을 때, 함수가 실질적으로 특정 함수 내에서 무한루프를 돌기 때문에 main.c 파일 내에 getch() 함수의 경우 삭제해도 잘 돌아가던 것으로 기억합니다.  따라서 main 내의 getch()함수를 삭제해도 상관없을듯 합니다.
