### ISSUE TITLE
block 출력이 제대로 되지 않습니다.

### ISSUE THREAD

**Issue by 4z7l** [myujin/OSS-Snake#15]
visual studio 2017 기준,
코드대로라면 block이 H로 출력이 되어야하는데 출력이 되지않습니다.
@myujin 님도 똑같은 오류가 발생하는지 확인 부탁드립니다

**Comment by myujin** [comment]
저희 프로젝트의 코드를 살펴 보면, 맵을 그리는 함수가 두 가지가 존재합니다. 

1. map_boundary()
2. map_block()

map_boundary() 함수는 게임 화면에서 1번 Quick game에서 실제로 맵의 경계를 출력하는데 사용되는 함수입니다. 그리고, map_block()함수는 게임 화면에서 2번 Customized game에서 사용되는 함수입니다.

현재 master branch에서의 소스코드를 확인하여 보면, map_boundary() 함수에서 H 대신 
A,B,E 등의 알파벳으로 출력 문자가 설정되어 있습니다.
따라서 map_boundary() 함수에서 goprint()의 함수에서 출력하는 문자를 'H'로 변경해주면 
block이 H 모양대로 출력될 것 입니다.

이 내용은 제가 소스 코드를 변경하여 push해 수정하도록 하겠습니다.
