### ISSUE TITLE
뱀이 맵의 상단과 좌측을 지나가면 경계를 출력하는 글자가 사라집니다

### ISSUE THREAD

**Issue by 4z7l** [myujin/OSS-Snake#16]
뱀이 맵의 상단과 좌측을 지나가면 경계를 출력하는 글자(D,C)가 사라집니다
또한, 그 경계에 food가 출력되는 경우가 있어 이를 해결할 방안을 모색중입니다.

**Comment by myujin** [comment]
이 issue는 아마 @4z7l 가 코드 개선작업을 진행하면서 map boundary의 좌표를 (0,n)의 좌표들도 추가하여 출력하면서 발생하는 문제인 것 같습니다. 이 문제에 대해서는 보다 정확히 코드를 확인해 보는 것이 정확하겠지만 

1. food_create() 함수
2. snake_move()함수

위의 두 가지 함수를 확인한 후, 각 함수의  for문에서 검사 범위를 조정해주면 문제가 해결될 것 같습니다.
