### ISSUE TITLE
'mod' 오류 

### ISSUE THREAD

**Issue by myujin** [myujin/OSS-Snake#18]
현재 프로젝트를 Visual Studio 2017에서 실행했을 경우 초기 화면에 

> 'mode' 는 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
> 배치 파일이 아닙니다. 

라는 메세지가 출력됩니다.  아마 interface.c 파일 내부의 
`system("mode con cols=140 lines=40");` 코드에서 문제가 발생하는 것 같습니다. 작업 도중 해결이 가능하다면 해결 부탁드립니다.

**Comment by 4z7l** [comment]
제 개발환경에서는 실행이 잘되어 확인해보니 mode.exe가 깔려있지 않은 컴퓨터에서 그런 오류가 뜬다고 합니다.
하지만 mode함수가 표준함수가 아니라고 하여 표준함수를 권장하자는 저희 프로젝트의 목표에 따라 mode함수를 다른 함수로 대체해보겠습니다.

**Comment by 4z7l** [comment]
참고 :
https://kin.naver.com/qna/detail.nhn?d1id=1&dirId=1040101&docId=150512937&qb=Y+yWuOyWtCDsvZjshpTssL0g7YGs6riw&enc=utf8&section=kin&rank=1&search_sort=0&spq=0&pid=UMyg7wp0JywssfzZn7NssssssRK-507845&sid=855bWc9USUvDQ%2B/8sBjnqg%3D%3D

**Comment by 4z7l** [comment]
이 오류를 수정하였는데, 실행이 되는지 확인 부탁드립니다.

**Comment by myujin** [comment]
방금 로컬 저장소에 fetch/merge하여 확인하여 보았는데, 잘 작동됩니다! 다만 초기 화면의 고정 크기와 게임 시작시 고정 크기가 달라 사이즈를 통일한다면 좀 더 좋을 것 같습니다~
