### ISSUE TITLE
과제 5 보고서 작성 양식 및 일정

### ISSUE THREAD

**Issue by myujin** [myujin/OSS-Snake#4]
### 보고서 마감일 : 보고서 제출 당일!
보고서 제출 당일 (5월 31일) 자정이 지나면 현재까지 구글 문서에서 작업한 내용을 
local 저장소로 옮겨 **워드 파일로 저장해 양식을 정리하고자 합니다**

###보고서 양식
구글 문서에서 작성할 때
- [ ]  1. 가장 큰 장은 18pt로 작성 / 볼드체 적용
- [ ]  1-1. 처럼 중간 장은 14pt로 작성 / 볼드체 적용
- [ ]  1-1-1. 처럼 가장 작은 단위의 장은 12pt로 작성 / 볼드체 적용
- [ ]  보고서 목차에는 페이지 작성하지 말 것
- [ ]  문단 시작할 때 첫 글자는 크게 표시
- [ ]  그림 첨부 시 표에 넣고 양식은 [그림 1-1-1] 식으로 작성 

@4z7l 
@myujin

**Comment by 4z7l** [comment]
- [ ] 문단 시작 시 들여쓰기

- [ ] 본문 폰트의 크기는 10pt

- [ ] 폰트는 맑은고딕

- [ ]  문단 시작 시 스페이스바 4번으로 들여쓰기 함
