### ISSUE TITLE
branch 이름 및 태그 이름에 관하여 

### ISSUE THREAD

**Issue by myujin** [myujin/OSS-Snake#5]
1. git tag를 아직 설정하지 않은 상태인데 기본적 버전 관리를 위한 tag를 설정하고자 합니다.
현재 간단하게 생각해 둔 방안은 

2. branch 이름을 정하는 방식을 '확실하게' 정하고자 합니다.
현재 존재하는 branch는  master,initError,renameFunc 총 세 개의 branch가 존재하는데,
이 세 개의 branch 이후로 추가적으로 생성하는 branch들에 대해서는 일정한 규칙에 맞게 그 이름을 작성하고자 합니다. 

생각해 둔 방안은 

1. 새로운 기능 시험용 branch >> [test] branch 생성하여 사용함 
2. Clean Code와 관련된 내용 >> [clean] 접두어 사용  

이 두 가지 정도만 생각해 둔 상태인데, 혹시 추가적으로 괜찮은 아이디어 있다면 댓글로 게시해주세요.

**Comment by 4z7l** [comment]
폴더 이름에 []와 같은 특수문자는 적합하지 않다고 생각합니다.

시험용 브랜치 : test_@@
가독성 개선 브랜치 : clean_@@ (함수명/변수명 수정 포함)
기능 수정 브랜치 : mod_@@
오류 수정 브랜치 : error_@@
삭제 브랜치 : del_@@

ex) del_globalvar, clean_func, clean_var, mod_map, error_snake ...

이외에도 '기능_세부사항' 등으로 브랜치를 작성하면 좋을 것 같습니다.

**Comment by myujin** [comment]
기능_ 세부사항 방식으로 작성하는게 확실히 좋은 아이디어인 것 같습니다!
그럼 앞으로 새로운 branch를 추가할 때는 말씀하신 내용 처럼 mod_@@ 등의 방식으로 추가하겠습니다. 
현재 맵의 출력 모양을 바꾸기 위해 새 branch를 추가할 예정인데 해당 branch의 이름은 
**mod_stage** 로 하겠습니다.

**Comment by 4z7l** [comment]
태그 작성 방안 :
콘솔창/ 게임화면 바뀌면 1추가
큰 오류/코드가 크게 바뀌면 0.1 추가
자잘한 오류/코드 수정 0.01추가
