### ISSUE TITLE
vi 편집기에서 인코딩 에러 

### ISSUE THREAD

**Issue by myujin** [myujin/OSS-Snake#7]
현재 저희 프로젝트에서 작업을 진행할 때, vi편집기에서 소스코드를 열 경우 '■' 과 같은 특수문자들을 인식하지 못하여 "?" 와 같은 오류로 출력이 됩니다. 그리고, **vi 편집기 내에서 해당 문자를 사용할 경우에는 파일이 제대로 저장이 되지 않는 등의 오류가 발생**합니다.  해당 문제점에 대한 해결 방안을 찾아보아야 할 것 같습니다.

**Comment by 4z7l** [comment]
입출력 시 특수문자를 이용하지 않고 알파벳을 사용하면 될 것 같습니다.

**Comment by myujin** [comment]
방법을 찾아보았는데, vi 편집기 내에서 utf-8과 유니코드 모두 인식하게 하는 방법이 없지는 않은 것 같습니다.
하지만 여러 작업 환경에서 오류가 발생하지 않는 것이 중요하니 알파벳을 사용하는게 현재로써는 최선 같지만.. 필드 모양을 깔끔하게 출력하지 못하는 점이 아쉬울 것 같습니다

**Comment by 4z7l** [comment]
ooooooooo
8　　　　8
8　　　　8
8　　　　8
ooooooooo

이런식으로 하면 그나마 괜찮지 않을까 싶네요.. ㅠㅠ
