### ISSUE TITLE
Commit 메세지 작성 방안

### ISSUE THREAD

**Issue by 4z7l** [myujin/OSS-Snake#8]
commit 메세지도 branch 이름과 비슷하게 양식을 통일하고자 합니다.

**짧은 commit 메세지 작성 시 :**
[Mod / Add / Del / Err 등.. ] - 간단한 설명

**긴 commit 메세지 작성 시 :** 
[Mod / Add / Del / Err 등.. ] - 간단한 설명
부연 설명과 commit 메세지를 작성한 날짜와 시간

또한, commit 메세지를 한글로 작성할 지 영어로 작성할지 통일시켜야할 것 같은데 
어떻게 할 지 고민되어 상의를 하고 싶습니다.

**Comment by myujin** [comment]
저는 한글로 통일하는게 해당 작업을 진행한 의도를 파악하기 더 쉬울 것 같습니다.  
그럼 지금 작업 부터는 말씀하신 안건 내용 처럼 양식을 통일하여 작성하기로 하고, 작업 마무리 단계에서 이전 commit 메세지들을 수정하는 것이 나을까요?

**Comment by 4z7l** [comment]
네! 이전 메세지는 시간이 남으면 수정하도록하고 이후 진행할 커밋 메세지 먼저 신경써서 하는 것도 괜찮을 것 같습니다
